version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Get latest ui-eholdings
          command: yarn upgrade @folio/eholdings
      - run:
          name: Copy ui-eholdings lockfile
          command: cp node_modules/@folio/eholdings/yarn.lock yarn.lock
      - run:
          name: Re-install dependencies
          command: yarn install
      - run:
          name: Build bundle
          command: NODE_ENV=production yarn build
      - run:
          name: Install AWS CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
              curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
              sudo pip install -q awscli --upgrade
            fi
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync dist s3://folio.frontside.io/ --acl public-read --cache-control max-age=30
            fi
