version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/ui-eholdings
    steps:
      - run:
          name: Check Out Repository
          command: |
            cd ~/
            git clone --branch=master https://github.com/folio-org/ui-eholdings.git
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build Bundle
          command: NODE_ENV=production yarn build
      - persist_to_workspace:
          root: ~/ui-eholdings
          paths:
            - dist
  deploy:
    docker:
      - image: cibuilds/aws
    working_directory: ~/ui-eholdings
    steps:
      - attach_workspace:
          at: ~/ui-eholdings
      - run:
          name: Deploy to S3
          command: aws s3 sync dist s3://folio.frontside.io/ --acl public-read --cache-control max-age=30

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
